FROM docker.pp.ua/magento2-php:latest

# PUT YOUR CODE HERE




#--------------------------------------------------------------------------
# REDIS
#----------------------------  ------------------------
RUN pecl install -o -f redis \
&&  docker-php-ext-enable redis
